abstract class Strings {
  static const appTitle = 'Первая практика';
  static const fileSystemScreen = 'Вывод файловой системы';
  static const fileWorkerScreen = 'Работа с файлом';
  static const jsonWorkerScreen = 'Работа с JSON файлом';
  static const xmlWorkerScreen = 'Работа с XML файлом';
  static const createFile = 'Создать файл';
  static const readFile = 'Прочитать содержимое файла';
  static const deleteFile = 'Удалить файл';
  static const enterFileContent = 'Введите содержимое текста';
  static const name = 'name';
  static const age = 'age';
  static const elementName = 'Название элемента';
  static const value = 'Значение';
  static const jsonFields = 'Поля JSON';
  static const newNestedElementValue = 'Новое значение вложенного поля';
  static const newNestedKeyValue = 'Новое имя вложенного поля';
  static const newValue = 'Новое значение';
  static const changeXmlValue = 'Изменить значения XML';
  static const zipWorkerScreen = 'Работа с ZIP архивами';
  static const createZipArchive = 'Создать ZIP архив';
  static const addFileToZip = 'Добавить файл в архив';
  static const extractZipArchive = 'Разархивировать';
  static const deleteFileAndZip = 'Удалить файл и архив';
  static const fileName = 'Имя файла';
  static const fileNameHint = 'Введите имя файла';
  static const extractPath = 'Путь для извлечения';
  static const extractPathHint = 'Введите путь для извлечения';
}
